services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  # nginx:

  # wordpress:
    
volumes:
  mariadb_data:

networks:
  inception:
    driver: bridge