CREATE DATABASE IF NOT EXISTS __MYSQL_DATABASE__;

USE __MYSQL_DATABASE__;

CREATE USER IF NOT EXISTS '__MYSQL_USER__'@'%' IDENTIFIED BY '__MYSQL_PASSWORD__';
GRANT ALL PRIVILEGES ON __MYSQL_DATABASE__.* TO '__MYSQL_USER__'@'%' WITH GRANT OPTION;

ALTER USER 'root'@'localhost' IDENTIFIED BY '__MYSQL_ROOT_PASSWORD__';

FLUSH PRIVILEGES;
